version: "3.9"

services:

  node-app:
    build: .
    environment:
      - NODE_ENV=dev
    ports:
      - "3000:3000"
    depends_on:
      - graphite
    networks:
      - node-net

  graphite:
    image: graphiteapp/graphite-statsd
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - node-net

networks:
  node-net:
    driver: bridge
